controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController 
    forward_command_controller:
      type: forward_command_controller/ForwardCommandController  

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [left_wheel_joint]
    right_wheel_names: [right_wheel_joint]
    wheel_separation: 0.105
    wheels_per_side: 2
    wheel_radius: 0.0325
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    publish_rate: 50.0
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    publish_odom: true
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    publish_odom: true
    enable_odom_tf: true

forward_command_controller:
  ros__parameters:
    joints: [arm_joint1, arm_joint2]
    interface_name: position